-- Phase 4: Data Health Dashboard Views (SQL)

-- 1. vw_data_completeness
-- Calculates the percentage of non-null values for key telemetry fields
CREATE MATERIALIZED VIEW vw_data_completeness AS
SELECT
    COUNT(*) AS total_records,
    COUNT(order_id) AS order_id_count,
    COUNT(tracking_id) AS tracking_id_count,
    COUNT(shipment_mode) AS shipment_mode_count,
    COUNT(delivery_date) AS delivery_date_count,
    COUNT(order_value) AS order_value_count,
    -- Compute completeness percentages
    ROUND((COUNT(order_id)::numeric / NULLIF(COUNT(*), 0)) * 100, 2) AS order_id_completeness_pct,
    ROUND((COUNT(tracking_id)::numeric / NULLIF(COUNT(*), 0)) * 100, 2) AS tracking_id_completeness_pct,
    ROUND((COUNT(shipment_mode)::numeric / NULLIF(COUNT(*), 0)) * 100, 2) AS shipment_mode_completeness_pct,
    ROUND((COUNT(delivery_date)::numeric / NULLIF(COUNT(*), 0)) * 100, 2) AS delivery_date_completeness_pct,
    ROUND((COUNT(order_value)::numeric / NULLIF(COUNT(*), 0)) * 100, 2) AS order_value_completeness_pct
FROM logistics_telemetry;


-- 2. vw_exception_backlog
-- Counts the number of unresolved errors in the exception logs by day
CREATE MATERIALIZED VIEW vw_exception_backlog AS
SELECT
    DATE(timestamp) AS exception_date,
    COUNT(*) AS total_exceptions,
    -- Since we don't have a resolution status column yet, we count all of them as backlog.
    -- If we added an 'is_resolved' boolean, it would look like: 
    -- SUM(CASE WHEN is_resolved = FALSE THEN 1 ELSE 0 END) as unresolved_count
    COUNT(*) AS unresolved_count
FROM exception_logs
GROUP BY DATE(timestamp)
ORDER BY exception_date DESC;


-- 3. vw_forecast_vs_actual
-- A view preparing actual aggregated sales vs time
-- (Note: Actual ARIMA predictions are generated by the Python FastAPI service on the fly. 
-- To materialize this in SQL, we either store the predictions back in a table or use a 
-- simplified moving average as a placeholder baseline for the BI tool.
-- Here we calculate the 7-day moving average of actuals as the "baseline_forecast" 
-- for comparison against actual ingested sales data.)
CREATE MATERIALIZED VIEW vw_forecast_vs_actual AS
WITH daily_sales AS (
    SELECT
        delivery_date AS date,
        SUM(order_value) AS actual_sales
    FROM logistics_telemetry
    WHERE delivery_date IS NOT NULL
    GROUP BY delivery_date
)
SELECT
    date,
    actual_sales,
    -- 7-day moving average as a baseline forecast
    AVG(actual_sales) OVER (
        ORDER BY date 
        ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING
    ) AS rolling_7d_forecast
FROM daily_sales
ORDER BY date;

-- To refresh these views later, run:
-- REFRESH MATERIALIZED VIEW vw_data_completeness;
-- REFRESH MATERIALIZED VIEW vw_exception_backlog;
-- REFRESH MATERIALIZED VIEW vw_forecast_vs_actual;
